#!/bin/sh
#============================================================+
# File name   : entrypoint.sh
# Begin       : 2026-06-22
#
# Description : Container entrypoint for the TCExam runtime image.
#               Runs the non-interactive installer (idempotent) so the stack
#               is ready without a browser install step, generates the
#               install-time build artifacts (PDF fonts and translation
#               caches) on first run, fixes runtime permissions, then executes
#               the container command (Apache).
#
# (c) Copyright 2004-2026 Nicola Asuni - Tecnick.com LTD
# License: AGPL-3.0-or-later (see LICENSE).
#============================================================+

set -e

APP=/var/www/html
FONTS="${APP}/vendor/tecnickcom/tc-lib-pdf-font/target/fonts"

# Warm the install-time artifacts. Run in the background (below) so Apache is available
# immediately: normal pages work at once (language caches also build lazily per request), and
# only PDF export depends on the fonts, which finish warming up shortly after start.
warm_artifacts() {
    # 1) PDF fonts — generated by tc-lib-pdf-font (downloads font sources); cached in the volume.
    if [ -d "${APP}/vendor/tecnickcom/tc-lib-pdf-font" ] && [ ! -d "${FONTS}/core" ]; then
        echo "[tcexam] generating PDF fonts (first run; this downloads font sources)…"
        if ! (cd "${APP}" && make fonts); then
            echo "[tcexam] WARNING: PDF font generation failed (network?). PDF export will not render until you run 'make fonts'." >&2
        fi
    fi

    # 2) Translation caches — cheap; regenerate if absent (also built lazily at runtime otherwise).
    if ! ls "${APP}/cache/lang"/*.php >/dev/null 2>&1; then
        echo "[tcexam] building language caches…"
        if ! (cd "${APP}" && make lang); then
            echo "[tcexam] WARNING: language cache build failed; caches will be built lazily per request." >&2
        fi
    fi

    # 3) Writable runtime paths owned by the web user (volumes mount as root by default).
    chown -R www-data:www-data "${APP}/cache" "${FONTS}" 2>/dev/null || true
}

# Zero-touch install: generate the configuration and load the database schema/data from the
# TCEXAM_* environment variables (see docker-compose.yml). Idempotent — on later starts it
# preserves an existing configuration and never overwrites existing data, so it is safe to run
# every time. Runs in the foreground so the site is configured before Apache starts serving.
CONFIG_DIRS="${APP}/shared/config ${APP}/admin/config ${APP}/public/config"
if [ -f "${APP}/install/install_cli.php" ]; then
    echo "[tcexam] running non-interactive installer…"
    if php "${APP}/install/install_cli.php"; then
        # The web user must be able to read the configuration (and write it during a later
        # web re-configuration); volumes mount as root by default.
        chown -R www-data:www-data ${CONFIG_DIRS} 2>/dev/null || true
    else
        echo "[tcexam] WARNING: automatic installation did not complete. The app may not be" >&2
        echo "[tcexam]          configured yet; you can finish it from the web installer at" >&2
        echo "[tcexam]          http://<host>:<port>/install/ ." >&2
    fi
fi

warm_artifacts &

exec "$@"
